# EDA for March Madness Data
## Summary Statistics

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
df = pd.read_csv("data/tournament_model_ml.csv")

# Quick glance
df.head()

,3P%_diff,AST_diff,FG%_diff,FT%_diff,SRS_diff,TOV_diff,TRB_diff,seed_diff,win_pct_diff,win_label,season
0,-0.019,56.0,-0.015,-0.036,26.50,16.0,218.0,-15,0.311,1,2015
1,0.072,-88.0,0.019,0.031,8.73,-29.0,24.0,-7,0.172,1,2015
2,-0.082,-61.0,-0.032,-0.016,14.49,12.0,153.0,-9,0.132,1,2015
3,0.044,16.0,0.024,-0.021,-2.73,8.0,-107.0,5,0.103,1,2015
4,-0.015,81.0,-0.003,-0.017,18.99,38.0,221.0,-11,-0.041,1,2015

In [11]:
# Categorical variables
categorical_vars = ["win_label", "season"]

# Numeric variables
numeric_vars = [col for col in df.columns if col not in categorical_vars]

numeric_vars, categorical_vars

(['3P%_diff',
  'AST_diff',
  'FG%_diff',
  'FT%_diff',
  'SRS_diff',
  'TOV_diff',
  'TRB_diff',
  'seed_diff',
  'win_pct_diff'],
 ['win_label', 'season'])

In [12]:
numeric_summary = df[numeric_vars].agg(
    ["count", "mean", "std"]
).T

numeric_summary

               count          mean         std
3P%_diff      1068.0  0.000000e+00    0.035930
AST_diff      1068.0  0.000000e+00  107.942364
FG%_diff      1068.0  4.158139e-19    0.033422
FT%_diff      1068.0  0.000000e+00    0.047550
SRS_diff      1068.0  0.000000e+00   12.358625
TOV_diff      1068.0  0.000000e+00   64.969187
TRB_diff      1068.0  0.000000e+00  172.544163
seed_diff     1068.0  0.000000e+00    7.848137
win_pct_diff  1068.0  0.000000e+00    0.147874

In [13]:
five_number_summary = df[numeric_vars].describe().T[
    ["min", "25%", "50%", "75%", "max"]
]

five_number_summary

                  min        25%  50%        75%      max
3P%_diff       -0.105   -0.02400  0.0    0.02400    0.105
AST_diff     -366.000  -74.25000  0.0   74.25000  366.000
FG%_diff       -0.122   -0.02200 -0.0    0.02200    0.122
FT%_diff       -0.163   -0.03225  0.0    0.03225    0.163
SRS_diff      -38.630   -7.41250  0.0    7.41250   38.630
TOV_diff     -239.000  -44.00000  0.0   44.00000  239.000
TRB_diff     -680.000 -117.25000 -0.0  117.25000  680.000
seed_diff     -15.000   -7.00000  0.0    7.00000   15.000
win_pct_diff   -0.488   -0.10100  0.0    0.10100    0.488

In [14]:
numeric_full_summary = numeric_summary.join(five_number_summary)
numeric_full_summary

,count,mean,std,min,25%,50%,75%,max
3P%_diff,1068.0,0.000000e+00,0.035930,-0.105,-0.02400,0.0,0.02400,0.105
AST_diff,1068.0,0.000000e+00,107.942364,-366.000,-74.25000,0.0,74.25000,366.000
FG%_diff,1068.0,4.158139e-19,0.033422,-0.122,-0.02200,-0.0,0.02200,0.122
FT%_diff,1068.0,0.000000e+00,0.047550,-0.163,-0.03225,0.0,0.03225,0.163
SRS_diff,1068.0,0.000000e+00,12.358625,-38.630,-7.41250,0.0,7.41250,38.630
TOV_diff,1068.0,0.000000e+00,64.969187,-239.000,-44.00000,0.0,44.00000,239.000
TRB_diff,1068.0,0.000000e+00,172.544163,-680.000,-117.25000,-0.0,117.25000,680.000
seed_diff,1068.0,0.000000e+00,7.848137,-15.000,-7.00000,0.0,7.00000,15.000
win_pct_diff,1068.0,0.000000e+00,0.147874,-0.488,-0.10100,0.0,0.10100,0.488

In [15]:
for col in categorical_vars:
    print(f"\n=== {col.upper()} ===")
    print("Sample Size:", df[col].count())
    print(df[col].value_counts())

=== WIN_LABEL ===
Sample Size: 1068
win_label
1    534
0    534
Name: count, dtype: int64

=== SEASON ===
Sample Size: 1068
season
2018    114
2015    112
2019    110
2025    108
2021    106
2017    106
2024    104
2022    104
2016    102
2023    102
Name: count, dtype: int64

In [16]:
correlation_matrix = df[numeric_vars].corr()
correlation_matrix

,3P%_diff,AST_diff,FG%_diff,FT%_diff,SRS_diff,TOV_diff,TRB_diff,seed_diff,win_pct_diff
3P%_diff,1.000000,0.377422,0.582878,0.271383,0.217466,-0.188244,-0.027122,-0.182182,0.302916
AST_diff,0.377422,1.000000,0.606446,0.137013,0.561088,0.149373,0.538355,-0.495156,0.504211
FG%_diff,0.582878,0.606446,1.000000,0.206220,0.347916,-0.063254,0.156278,-0.291044,0.519371
FT%_diff,0.271383,0.137013,0.206220,1.000000,0.208818,-0.217719,-0.085450,-0.190244,0.128055
SRS_diff,0.217466,0.561088,0.347916,0.208818,1.000000,-0.034144,0.559851,-0.933950,0.547559
TOV_diff,-0.188244,0.149373,-0.063254,-0.217719,-0.034144,1.000000,0.404907,0.009216,-0.119918
TRB_diff,-0.027122,0.538355,0.156278,-0.085450,0.559851,0.404907,1.000000,-0.523486,0.461096
seed_diff,-0.182182,-0.495156,-0.291044,-0.190244,-0.933950,0.009216,-0.523486,1.000000,-0.543627
win_pct_diff,0.302916,0.504211,0.519371,0.128055,0.547559,-0.119918,0.461096,-0.543627,1.000000

In [18]:


corr_table = (
    df[numeric_vars + ["win_label"]]
    .corr()
    [["win_label"]]
    .rename(columns={"win_label": "Correlation with Win"})
    .sort_values("Correlation with Win", ascending=False)
    .round(3)
)

corr_table

              Correlation with Win
win_label                    1.000
SRS_diff                     0.547
TRB_diff                     0.463
AST_diff                     0.391
win_pct_diff                 0.354
FG%_diff                     0.191
FT%_diff                     0.138
3P%_diff                     0.135
TOV_diff                     0.109
seed_diff                   -0.491